import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, CalendarDays, CloudSun, Folder, LocateFixed, LockKeyhole, Moon, Search, Settings, Sun } from "lucide-react";
import { Link } from "react-router-dom";
import { PortalBackground } from "../components/PortalBackground";
import { PortalBackgroundSettings } from "../components/PortalBackgroundSettings";
import { ManagedPortalIcon } from "../components/PortalIcon";
import { PortalPalettePicker } from "../components/PortalPalettePicker";
import { initialPortalConfig, type PortalConfig } from "../data/portalSites";
import { portalAppearance } from "../data/portalAppearance";
import { portalApi, type WeatherResponse } from "../lib/portalApi";
import { externalSearchUrl, matchesPortalSite, type SearchMode } from "../lib/portalSearch";
import { portalBackgroundStore } from "../stores/portalBackground";
import { portalPaletteStore } from "../stores/portalPalette";

const searchLabels: Record<SearchMode, string> = { local: "本地", google: "Google", bing: "Bing", duckduckgo: "DuckDuckGo" };
const weatherText = (code: number) => code === 0 ? "晴朗" : code <= 3 ? "多云" : code <= 48 ? "雾" : code <= 67 ? "有雨" : code <= 77 ? "有雪" : code <= 82 ? "阵雨" : code <= 99 ? "雷雨" : "天气变化";
function ClockWidget() { const [now, setNow] = useState(() => new Date()); useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []); const date = new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "long" }).format(now); let lunar = "农历信息"; try { lunar = new Intl.DateTimeFormat("zh-CN-u-ca-chinese", { month: "long", day: "numeric" }).format(now); } catch { /* Stable fallback for old browsers. */ } return <section className="portal-widget portal-clock" aria-label="本地时间"><CalendarDays size={20} aria-hidden="true" /><div><time dateTime={now.toISOString()}>{now.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time><p>{date} · {lunar}</p></div></section>; }
function WeatherWidget({ config }: { config: PortalConfig }) { const { settings } = config; const [weather, setWeather] = useState<WeatherResponse | null>(null); const [state, setState] = useState("正在获取天气…"); const load = (lat?: number, lon?: number, city?: string) => { setState("正在获取天气…"); return portalApi.weather(lat, lon, city).then((value) => { setWeather(value); setState(""); }).catch(() => { setWeather(null); setState("天气暂时不可用"); }); }; useEffect(() => { let active = true; portalApi.weather().catch(() => portalApi.weather(settings.latitude, settings.longitude, settings.defaultCity)).then((value) => { if (!active) return; setWeather(value); setState(""); }).catch(() => { if (!active) return; setWeather(null); setState("天气暂时不可用"); }); return () => { active = false; }; }, [settings.latitude, settings.longitude, settings.defaultCity]); const locate = () => { if (!navigator.geolocation) { setState("浏览器不支持定位"); return; } setState("正在请求精确位置…"); navigator.geolocation.getCurrentPosition((position) => { void load(position.coords.latitude, position.coords.longitude, "精确位置"); }, () => setState("未获得位置权限"), { timeout: 10000, maximumAge: 600000 }); }; return <section className="portal-widget portal-weather" aria-label="天气"><CloudSun size={21} aria-hidden="true" /><div className="portal-weather-main">{weather ? <><strong>{Math.round(weather.current.temperature)}°</strong><span>{weather.location} · {weatherText(weather.current.weatherCode)}<small>体感 {Math.round(weather.current.apparentTemperature)}° · 明日 {Math.round(weather.forecast[1]?.minimum ?? 0)}°–{Math.round(weather.forecast[1]?.maximum ?? 0)}°</small></span></> : <span>{state}</span>}</div><button type="button" onClick={locate} aria-label="使用浏览器精确定位查看天气" title="使用浏览器精确定位"><LocateFixed size={17} /></button></section>; }

export function PortalStartPage({ dark, onTheme }: { dark: boolean; onTheme: () => void }) {
  const [background, setBackground] = useState(() => portalBackgroundStore.get()); const [palette, setPalette] = useState(() => portalPaletteStore.get()); const [config, setConfig] = useState<PortalConfig>(initialPortalConfig); const [query, setQuery] = useState(""); const [categoryId, setCategoryId] = useState("all"); const [folderId, setFolderId] = useState<string | null>(null); const [mode, setMode] = useState<SearchMode>(() => { const saved = localStorage.getItem("hfdz-navigation:search-mode"); return saved && saved in searchLabels ? saved as SearchMode : "local"; });
  useEffect(() => { void portalApi.publicSites().then(setConfig).catch(() => undefined); }, []);
  const categories = useMemo(() => config.categories.filter((item) => !item.hidden).sort((a, b) => a.order - b.order), [config.categories]); const currentFolder = config.folders.find((item) => item.id === folderId);
  const visibleSites = useMemo(() => { const visibleCategoryIds = new Set(categories.map((item) => item.id)); return config.sites.filter((site) => visibleCategoryIds.has(site.categoryId) && (categoryId === "all" || site.categoryId === categoryId) && (!folderId ? !site.folderId : site.folderId === folderId) && matchesPortalSite(site, config.categories.find((item) => item.id === site.categoryId), query)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || a.order - b.order); }, [config, categories, categoryId, folderId, query]);
  const visibleFolders = useMemo(() => folderId ? [] : config.folders.filter((folder) => (categoryId === "all" || folder.categoryId === categoryId) && config.sites.some((site) => site.folderId === folder.id && matchesPortalSite(site, config.categories.find((item) => item.id === site.categoryId), query))).sort((a, b) => a.order - b.order), [config, categoryId, folderId, query]);
  const submitSearch = (event: FormEvent) => { event.preventDefault(); if (mode !== "local" && query.trim()) window.location.assign(externalSearchUrl(mode, query)); }; const chooseMode = (next: SearchMode) => { setMode(next); localStorage.setItem("hfdz-navigation:search-mode", next); };
  return <main className="portal-page portal-start-page" id="main-content" data-portal-palette={palette} data-density={config.settings.density}><PortalBackground src={background ?? portalAppearance.backgroundImage} fallbackSrc={portalAppearance.backgroundImage} /><section className="portal-glass portal-start-glass" aria-label="HFDZ Home">
    <header className="portal-toolbar"><Link className="portal-brand" to="/" aria-label="HFDZ Home"><img src="/favicon.svg" alt="" /><strong>HFDZ</strong><span>Home</span></Link><form className="portal-search" onSubmit={submitSearch}><select aria-label="搜索方式" value={mode} onChange={(event) => chooseMode(event.target.value as SearchMode)}>{Object.entries(searchLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><Search size={18} aria-hidden="true" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={mode === "local" ? "搜索网站、域名或分类" : `使用 ${searchLabels[mode]} 搜索`} aria-label="搜索" /><button type="submit" aria-label="提交搜索"><ArrowUpRight size={17} /></button></form><div className="portal-tools"><PortalPalettePicker value={palette} onChange={(value) => setPalette(portalPaletteStore.set(value))} /><PortalBackgroundSettings currentUrl={background} onApply={(url) => setBackground(portalBackgroundStore.set(url))} onReset={() => { portalBackgroundStore.clear(); setBackground(null); }} /><button className="portal-tool-icon" type="button" onClick={onTheme} aria-label={dark ? "切换浅色模式" : "切换深色模式"}>{dark ? <Sun size={17} /> : <Moon size={17} />}</button><Link className="portal-tool-icon" to="/manage" aria-label="设置与管理网站" title="设置与管理网站"><Settings size={18} /></Link></div></header>
    {(config.settings.clockEnabled || config.settings.weatherEnabled) && <div className="portal-widgets">{config.settings.clockEnabled && <ClockWidget />}{config.settings.weatherEnabled && <WeatherWidget config={config} />}</div>}
    <nav className="portal-categories" aria-label="网站分类"><button className={categoryId === "all" ? "active" : ""} onClick={() => { setCategoryId("all"); setFolderId(null); }}>全部</button>{categories.map((category) => <button className={categoryId === category.id ? "active" : ""} key={category.id} onClick={() => { setCategoryId(category.id); setFolderId(null); }}>{category.name}</button>)}</nav>
    {currentFolder && <div className="portal-breadcrumb"><button type="button" onClick={() => setFolderId(null)}><ArrowLeft size={16} />返回</button><span>/</span><strong>{currentFolder.name}</strong></div>}
    <div className="portal-grid portal-compact-grid" aria-live="polite">{visibleFolders.map((folder) => { const count = config.sites.filter((site) => site.folderId === folder.id).length; return <button className="portal-link portal-folder" key={folder.id} onClick={() => setFolderId(folder.id)}><span className="portal-icon"><Folder size={23} /></span><span className="portal-link-copy"><strong>{folder.name}</strong><span className="portal-description">{count} 个网站</span><span className="portal-hostname">打开文件夹</span></span><ArrowUpRight className="portal-link-arrow" size={17} /></button>; })}{visibleSites.map((site) => <a className="portal-link" href={site.url} key={site.id}><span className="portal-icon" aria-hidden="true"><ManagedPortalIcon iconUrl={site.iconUrl} hostname={site.hostname} /></span><span className="portal-link-copy"><span className="portal-link-heading"><strong>{site.name}</strong>{site.access === "authenticated" && <LockKeyhole size={12} aria-label="登录使用" />}</span><span className="portal-description">{site.description}</span><span className="portal-hostname">{site.hostname}</span></span><ArrowUpRight className="portal-link-arrow" size={17} aria-hidden="true" /></a>)}</div>{!visibleFolders.length && !visibleSites.length && <p className="portal-empty">没有找到匹配的网站。</p>}
  </section></main>;
}
