import { ArrowLeft, BookOpen, ExternalLink, Github, Heart, Monitor, Network, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Link, Navigate, useParams } from "react-router-dom";
import { getAlternatives, getRelated, getResource, getResourceCategory, getResourceTags } from "../lib/catalog";
import { loadKnowledgeIndex, matchKnowledge, type KnowledgeArticle } from "../lib/knowledge";
import { BrandIcon } from "../components/BrandIcon";
import { ResourceCard } from "../components/ResourceCard";
const markdownFiles = import.meta.glob("../content/resources/*.md", { eager: true, query: "?raw", import: "default" }) as Record<string, string>;
const labels = { free: "免费", freemium: "免费增值", paid: "付费", "open-source": "开源", proprietary: "专有", easy: "容易", medium: "中等", advanced: "进阶", direct: "直连", proxy: "需代理", unknown: "待验证" };
const stale = (date: string) => Date.now() - new Date(date).getTime() > 365 * 24 * 60 * 60 * 1000;
export function ResourcePage({ favoriteIds, toggleFavorite }: { favoriteIds: string[]; toggleFavorite: (id: string) => void }) {
  const { id } = useParams(); const resource = id ? getResource(id) : undefined; const [articles, setArticles] = useState<KnowledgeArticle[] | null>(null);
  useEffect(() => { const controller = new AbortController(); loadKnowledgeIndex(controller.signal).then(setArticles).catch(() => setArticles([])); return () => controller.abort(); }, []);
  if (!resource) return <Navigate to="/" replace />;
  const category = getResourceCategory(resource); const tags = getResourceTags(resource); const markdown = resource.detailPath ? markdownFiles[`../content/resources/${resource.detailPath}`] : undefined; const automatic = useMemo(() => articles ? matchKnowledge(resource, articles) : [], [articles, resource]); const alternatives = getAlternatives(resource); const related = getRelated(resource);
  return <main className="detail-page"><Link className="back-link" to="/"><ArrowLeft size={17} />返回 HFDZ Curates</Link>
    <section className="detail-hero"><BrandIcon icon={resource.icon} name={resource.name} size="md" /><div><p className="eyebrow">{category.name} · 编辑评分</p><div className="detail-title"><h1>{resource.name}</h1><span className={`rating rating-${resource.rating.toLowerCase()}`}>{resource.rating}</span></div><p>{resource.description}</p><div className="tag-row">{tags.map((tag) => <span className={`tag tag-${tag.color}`} key={tag.id}>#{tag.name}</span>)}</div></div><button className={`detail-favorite ${favoriteIds.includes(resource.id) ? "active" : ""}`} onClick={() => toggleFavorite(resource.id)}><Heart size={17} fill={favoriteIds.includes(resource.id) ? "currentColor" : "none"} />{favoriteIds.includes(resource.id) ? "已收藏" : "收藏"}</button></section>
    <div className="detail-layout"><article className="detail-content">{resource.editorial && <section className="editorial"><p className="eyebrow">为什么收录</p><p>{resource.editorial.verdict}</p></section>}<section className="metadata"><div><Sparkles size={17} /><span>适合人群与难度</span><b>需要 {labels[resource.difficulty]} 上手的使用者</b></div><div><Network size={17} /><span>网络</span><b>{labels[resource.networkAccess]}{resource.networkAccessCheckedAt ? ` · ${resource.networkAccessCheckedAt}` : ""}</b></div><div><Monitor size={17} /><span>平台 / 价格 / 授权</span><b>{resource.platforms.join(" / ")} · {labels[resource.pricing]} · {labels[resource.license]}</b></div></section>{stale(resource.updatedAt) && <p className="review-note">内容待复核</p>}{markdown ? <ReactMarkdown>{markdown}</ReactMarkdown> : <p className="no-detail">此资源暂未添加 Markdown 详情，可直接访问官方链接获取最新资料。</p>}
      {(resource.editorial?.tutorials.length || automatic.length > 0) && <section className="knowledge-links"><h2>Quartz 教程与笔记</h2>{resource.editorial?.tutorials.map((item) => <a key={item.url} href={item.url} target="_blank" rel="noreferrer"><BookOpen size={16} />{item.title}<ExternalLink size={14} /></a>)}{automatic.map((article) => <a key={article.url} href={article.url} target="_blank" rel="noreferrer"><BookOpen size={16} />{article.title}<ExternalLink size={14} /></a>)}</section>}</article>
      <aside className="detail-sidebar"><h2>官方链接</h2><a href={resource.links.website} target="_blank" rel="noreferrer"><ExternalLink size={16} />官网</a>{resource.links.github && <a href={resource.links.github} target="_blank" rel="noreferrer"><Github size={16} />GitHub</a>}{resource.links.docs && <a href={resource.links.docs} target="_blank" rel="noreferrer"><BookOpen size={16} />文档</a>}<small>更新时间：{resource.updatedAt}</small></aside></div>
    {alternatives.length > 0 && <RelatedSection title="替代方案" caption="明确标注的可替代产品" items={alternatives} favoriteIds={favoriteIds} toggle={toggleFavorite} />}
    <RelatedSection title="相关推荐" caption="按分类、共同标签、评分与日期排序" items={related} favoriteIds={favoriteIds} toggle={toggleFavorite} />
  </main>;
}
function RelatedSection({ title, caption, items, favoriteIds, toggle }: { title: string; caption: string; items: ReturnType<typeof getRelated>; favoriteIds: string[]; toggle: (id: string) => void }) { return <section className="content-section related"><div className="section-heading"><div><p className="eyebrow">DISCOVER</p><h2>{title}</h2></div><span>{caption}</span></div><div className="resource-grid">{items.map((item) => <ResourceCard key={item.id} resource={item} favorite={favoriteIds.includes(item.id)} onToggleFavorite={toggle} variant="compact" />)}</div></section>; }
