import { useEffect, useMemo, useState } from "react";
import { Clock3, CloudSun, LocateFixed, Pause, Play, RotateCcw } from "lucide-react";
import type { PortalConfig } from "../data/portalSites";
import { portalApi, type WeatherResponse } from "../lib/portalApi";

const weatherText = (code: number) => code === 0 ? "晴朗" : code <= 3 ? "多云" : code <= 48 ? "雾" : code <= 67 ? "有雨" : code <= 77 ? "有雪" : code <= 82 ? "阵雨" : code <= 99 ? "雷雨" : "天气变化";
const cities = [{ name: "香港", zone: "Asia/Hong_Kong" }, { name: "东京", zone: "Asia/Tokyo" }, { name: "伦敦", zone: "Europe/London" }, { name: "纽约", zone: "America/New_York" }];

export function ClockWidget() {
  const [now, setNow] = useState(() => new Date()); const [expanded, setExpanded] = useState(false); const [mode, setMode] = useState<"focus" | "break">("focus"); const [remaining, setRemaining] = useState(25 * 60); const [running, setRunning] = useState(false);
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setRemaining((value) => { if (value <= 1) { setRunning(false); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [running]);
  const setTimerMode = (next: "focus" | "break") => { setMode(next); setRemaining(next === "focus" ? 25 * 60 : 5 * 60); setRunning(false); };
  const time = `${String(Math.floor(remaining / 60)).padStart(2, "0")}:${String(remaining % 60).padStart(2, "0")}`;
  return <section className={`portal-widget portal-clock${expanded ? " is-expanded" : ""}`} aria-label="时间与番茄钟"><button className="portal-widget-summary" type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}><Clock3 size={20} /><span><time dateTime={now.toISOString()}>{now.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}</time><small>{new Intl.DateTimeFormat("zh-CN", { month: "long", day: "numeric", weekday: "short" }).format(now)}</small></span></button>{expanded && <div className="portal-widget-detail"><div className="portal-world-clocks">{cities.map((city) => <span key={city.zone}><small>{city.name}</small><strong>{now.toLocaleTimeString("zh-CN", { timeZone: city.zone, hour: "2-digit", minute: "2-digit", hour12: false })}</strong></span>)}</div><div className="portal-pomodoro"><div className="portal-segmented"><button className={mode === "focus" ? "active" : ""} onClick={() => setTimerMode("focus")}>专注 25</button><button className={mode === "break" ? "active" : ""} onClick={() => setTimerMode("break")}>休息 5</button></div><output>{time}</output><div><button type="button" onClick={() => setRunning((value) => !value)} aria-label={running ? "暂停番茄钟" : "开始番茄钟"}>{running ? <Pause size={16} /> : <Play size={16} />}</button><button type="button" onClick={() => { setRunning(false); setRemaining(mode === "focus" ? 25 * 60 : 5 * 60); }} aria-label="重置番茄钟"><RotateCcw size={16} /></button></div></div></div>}</section>;
}

export function WeatherWidget({ config }: { config: PortalConfig }) {
  const { settings } = config; const [weather, setWeather] = useState<WeatherResponse | null>(null); const [state, setState] = useState("正在获取天气…"); const [expanded, setExpanded] = useState(false);
  const load = (lat?: number, lon?: number, city?: string) => { setState("正在获取天气…"); return portalApi.weather(lat, lon, city).then((value) => { setWeather(value); setState(""); }).catch(() => { setWeather(null); setState("天气暂时不可用"); }); };
  useEffect(() => { let active = true; portalApi.weather().catch(() => portalApi.weather(settings.latitude, settings.longitude, settings.defaultCity)).then((value) => { if (active) { setWeather(value); setState(""); } }).catch(() => { if (active) setState("天气暂时不可用"); }); return () => { active = false; }; }, [settings]);
  const locate = () => { if (!navigator.geolocation) return setState("浏览器不支持定位"); setState("正在请求精确位置…"); navigator.geolocation.getCurrentPosition((position) => void load(position.coords.latitude, position.coords.longitude, "精确位置"), () => setState("未获得位置权限"), { timeout: 10000, maximumAge: 600000 }); };
  const forecast = useMemo(() => weather?.forecast.slice(0, 3) ?? [], [weather]);
  return <section className={`portal-widget portal-weather${expanded ? " is-expanded" : ""}`} aria-label="天气"><button className="portal-widget-summary" type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded}><CloudSun size={21} />{weather ? <span><strong>{Math.round(weather.current.temperature)}°</strong><small>{weather.location} · {weatherText(weather.current.weatherCode)}</small></span> : <span><small>{state}</small></span>}</button><button className="portal-locate" type="button" onClick={locate} aria-label="使用浏览器精确定位"><LocateFixed size={17} /></button>{expanded && weather && <div className="portal-widget-detail"><dl className="portal-weather-metrics"><div><dt>湿度</dt><dd>{Math.round(weather.current.humidity)}%</dd></div><div><dt>风速</dt><dd>{Math.round(weather.current.windSpeed)} km/h</dd></div><div><dt>AQI</dt><dd>{weather.current.aqi === null ? "不可用" : Math.round(weather.current.aqi)}</dd></div><div><dt>UV</dt><dd>{weather.current.uvIndex === null ? "不可用" : weather.current.uvIndex.toFixed(1)}</dd></div></dl><div className="portal-forecast">{forecast.map((day) => <span key={day.date}><small>{new Intl.DateTimeFormat("zh-CN", { weekday: "short" }).format(new Date(`${day.date}T12:00:00`))}</small><strong>{weatherText(day.weatherCode)}</strong><em>{Math.round(day.minimum)}°–{Math.round(day.maximum)}°</em></span>)}</div></div>}</section>;
}
