const CATALOG_KEY = "portal_sites:v1";
const MAX_SITES = 100;
const DEFAULT_CATEGORY = { id: "category-default", name: "我的网页", order: 0, hidden: false, palette: "aurora" };
const DEFAULT_SETTINGS = { clockEnabled: true, weatherEnabled: true, defaultCity: "香港", latitude: 22.3193, longitude: 114.1694, density: "compact" };
const DEFAULT_SITES = [
  { id: "portfolio", name: "个人主页", description: "作品、经历与关于我的一切。", url: "https://me.hfdz1119.top/", hostname: "me.hfdz1119.top", iconUrl: "/favicon.svg", category: "我的网页", emphasis: "primary", access: "public", pinned: true, order: 0 },
  { id: "notes", name: "私人笔记", description: "写作、整理与沉淀想法的私人空间。", url: "https://kb.hfdz1119.top/", hostname: "kb.hfdz1119.top", category: "我的网页", emphasis: "standard", access: "authenticated", pinned: false, order: 1 },
  { id: "knowledge", name: "公开知识库", description: "经过筛选后公开分享的知识与记录。", url: "https://wiki.hfdz1119.top/", hostname: "wiki.hfdz1119.top", category: "我的网页", emphasis: "standard", access: "public", pinned: false, order: 2 },
  { id: "images", name: "图片管理", description: "上传、管理并获取稳定的图片链接。", url: "https://image.hfdz1119.top/", hostname: "image.hfdz1119.top", category: "我的网页", emphasis: "standard", access: "public", pinned: false, order: 3 },
  { id: "status", name: "服务状态", description: "查看网站与服务当前是否正常运行。", url: "https://status.hfdz1119.top/", hostname: "status.hfdz1119.top", category: "我的网页", emphasis: "standard", access: "public", pinned: false, order: 4 },
];

export const json = (value, status = 200, headers = {}) => new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...headers } });
function asText(value, field, maximum, required = true) { if (typeof value !== "string") { if (!required && (value === undefined || value === null)) return ""; throw new Error(`${field}格式不正确。`); } const text = value.trim(); if (required && !text) throw new Error(`${field}不能为空。`); if (text.length > maximum) throw new Error(`${field}过长。`); return text; }
function httpsUrl(value, field, required = true) { const text = asText(value, field, 2048, required); if (!text && !required) return ""; let url; try { url = new URL(text); } catch { throw new Error(`${field}不是有效链接。`); } if (url.protocol !== "https:" || url.username || url.password) throw new Error(`${field}必须是安全的 HTTPS 链接。`); return url; }

export function siteUrlKey(value) { const url = value instanceof URL ? new URL(value.href) : new URL(value); url.hash = ""; url.hostname = url.hostname.toLowerCase(); if (url.protocol === "https:" && url.port === "443") url.port = ""; url.pathname = url.pathname.replace(/\/+$/, "") || "/"; return url.href; }
export function hasDuplicateSite(sites, url, excludedId) { const candidate = siteUrlKey(url); return sites.some((site) => site.id !== excludedId && siteUrlKey(site.url) === candidate); }
export function migrateCatalog(raw) { const sourceSites = Array.isArray(raw?.sites) ? raw.sites : DEFAULT_SITES; if (raw?.version === 2 && Array.isArray(raw.categories) && Array.isArray(raw.folders) && raw.settings) return { version: 2, sites: sourceSites, categories: raw.categories, folders: raw.folders, settings: { ...DEFAULT_SETTINGS, ...raw.settings } }; return { version: 2, sites: sourceSites.map((site) => ({ ...site, category: site.category || DEFAULT_CATEGORY.name, categoryId: DEFAULT_CATEGORY.id })), categories: [DEFAULT_CATEGORY], folders: [], settings: DEFAULT_SETTINGS }; }
export function validateSite(input, existing = {}, config = migrateCatalog(null)) { const url = httpsUrl(input.url, "网站地址"); const iconUrl = httpsUrl(input.iconUrl, "图标地址", false); const category = config.categories.find((item) => item.id === input.categoryId) ?? config.categories[0]; if (!category) throw new Error("请先创建分类。"); const folder = input.folderId ? config.folders.find((item) => item.id === input.folderId && item.categoryId === category.id) : null; if (input.folderId && !folder) throw new Error("文件夹与分类不匹配。"); return { id: existing.id ?? crypto.randomUUID(), name: asText(input.name, "网站名称", 80), description: asText(input.description, "简介", 180), url: url.href, hostname: url.hostname, ...(iconUrl ? { iconUrl: iconUrl.href } : {}), category: category.name, categoryId: category.id, ...(folder ? { folderId: folder.id } : {}), emphasis: input.emphasis === "primary" ? "primary" : "standard", access: input.access === "authenticated" ? "authenticated" : "public", pinned: input.pinned === true, order: Number.isInteger(input.order) && input.order >= 0 && input.order <= MAX_SITES * 10 ? input.order : (existing.order ?? 0) }; }
const validPalette = (value) => ["aurora", "sakura", "lavender", "sunset"].includes(value) ? value : "aurora";
export function validatePublicConfig(input, current) { const categories = Array.isArray(input.categories) ? input.categories.slice(0, 30).map((item, index) => ({ id: asText(item.id, "分类 ID", 80), name: asText(item.name, "分类名称", 40), order: Number.isInteger(item.order) ? item.order : index, hidden: item.hidden === true, palette: validPalette(item.palette) })) : current.categories; if (!categories.length) throw new Error("至少保留一个分类。"); const categoryIds = new Set(categories.map((item) => item.id)); if (categoryIds.size !== categories.length) throw new Error("分类 ID 不能重复。"); const folders = Array.isArray(input.folders) ? input.folders.slice(0, 50).map((item, index) => { if (!categoryIds.has(item.categoryId)) throw new Error("文件夹必须属于有效分类。"); return { id: asText(item.id, "文件夹 ID", 80), name: asText(item.name, "文件夹名称", 40), categoryId: item.categoryId, order: Number.isInteger(item.order) ? item.order : index }; }) : current.folders; const settingsInput = input.settings ?? current.settings; const latitude = Number(settingsInput.latitude); const longitude = Number(settingsInput.longitude); if (!Number.isFinite(latitude) || latitude < -90 || latitude > 90 || !Number.isFinite(longitude) || longitude < -180 || longitude > 180) throw new Error("天气经纬度无效。"); return { categories, folders, settings: { clockEnabled: settingsInput.clockEnabled !== false, weatherEnabled: settingsInput.weatherEnabled !== false, defaultCity: asText(settingsInput.defaultCity, "默认城市", 60), latitude, longitude, density: settingsInput.density === "comfortable" ? "comfortable" : "compact" } }; }
export async function readConfig(env) { if (!env.HFDZ_NAVIGATION_KV) throw new Error("HFDZ_NAVIGATION_KV 尚未绑定。"); return migrateCatalog(await env.HFDZ_NAVIGATION_KV.get(CATALOG_KEY, "json")); }
export async function writeConfig(env, config) { if (!env.HFDZ_NAVIGATION_KV) throw new Error("HFDZ_NAVIGATION_KV 尚未绑定。"); await env.HFDZ_NAVIGATION_KV.put(CATALOG_KEY, JSON.stringify({ ...config, version: 2 })); }
export { CATALOG_KEY, DEFAULT_CATEGORY, DEFAULT_SETTINGS, MAX_SITES };
